"""Merge hub pre-commit config with a spoke-local overlay.

During hub-spoke sync, ``.pre-commit-config.yaml`` is overwritten with the hub
version.  Spokes that define spoke-only hooks in
``.pre-commit-config.local.yaml`` need those hooks preserved after sync.

This module provides :func:`merge_precommit_config` which appends the overlay's
``repos:`` entries after the hub repos, producing a single merged config.
"""

from __future__ import annotations

import enum
import shutil
from pathlib import Path

import yaml

LOCAL_OVERLAY = ".pre-commit-config.local.yaml"


class _IndentedListDumper(yaml.SafeDumper):
    """YAML dumper that indents sequence items under their mapping key.

    Default ``SafeDumper`` emits sequences flush with the parent key
    (``- repo:`` at the same level as ``repos:``).  This subclass indents
    them so that ``yamllint indent-sequences: true`` passes.
    """


def _indented_list_representer(dumper: _IndentedListDumper, data: list) -> yaml.Node:
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=False)


_IndentedListDumper.add_representer(list, _indented_list_representer)

# Override increase_indent to set indentless=False for block sequences.
# The base class method signature is untyped in PyYAML stubs, so we
# override directly on the class to avoid protocol mismatch.
_original_increase_indent = _IndentedListDumper.increase_indent


def _increase_indent(
    self: _IndentedListDumper,
    flow: bool = False,
    indentless: bool = False,
) -> None:
    return _original_increase_indent(self, flow=flow, indentless=False)


_IndentedListDumper.increase_indent = _increase_indent  # type: ignore[assignment]

GENERATED_HEADER = (
    "# AUTO-GENERATED by sync-directives merge.\n"
    "# Hub hooks: .pre-commit-config.yaml (synced from repo-template)\n"
    "# Spoke hooks: .pre-commit-config.local.yaml (spoke-owned)\n"
    "# Do not edit directly. Modify .pre-commit-config.local.yaml for spoke-specific hooks.\n"
)

# Keys that are YAML anchor definitions (x-* extension keys) and should be
# stripped from merged output since anchors are expanded by safe_load.
_ANCHOR_PREFIX = "x-"


class MergeResult(enum.Enum):
    """Outcome of a merge operation."""

    PASSTHROUGH = "passthrough"
    MERGED = "merged"


def merge_precommit_config(
    hub_config: Path,
    target_dir: Path,
    output: Path,
) -> MergeResult:
    """Merge hub pre-commit config with spoke-local overlay.

    Returns :attr:`MergeResult.MERGED` if an overlay was applied,
    :attr:`MergeResult.PASSTHROUGH` if hub config was copied as-is.
    """
    overlay_path = target_dir / LOCAL_OVERLAY

    if not overlay_path.is_file():
        output.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(hub_config, output)
        return MergeResult.PASSTHROUGH

    overlay_data = yaml.safe_load(overlay_path.read_text(encoding="utf-8"))

    if not isinstance(overlay_data, dict) or "repos" not in overlay_data:
        output.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(hub_config, output)
        return MergeResult.PASSTHROUGH

    overlay_repos = overlay_data["repos"]
    if not isinstance(overlay_repos, list):
        msg = f"overlay repos must be a list, got {type(overlay_repos).__name__}: {overlay_path}"
        raise ValueError(msg)

    hub_data = yaml.safe_load(hub_config.read_text(encoding="utf-8"))

    if not isinstance(hub_data, dict):
        msg = f"hub config must be a mapping, got {type(hub_data).__name__}: {hub_config}"
        raise ValueError(msg)

    # Strip YAML anchor definition keys (e.g., x-python-wrapper) since
    # safe_load already expanded them into the consuming nodes.
    hub_data = {
        config_key: config_val
        for config_key, config_val in hub_data.items()
        if not config_key.startswith(_ANCHOR_PREFIX)
    }

    hub_repos = hub_data.get("repos", [])
    if not isinstance(hub_repos, list):
        msg = f"hub repos must be a list, got {type(hub_repos).__name__}: {hub_config}"
        raise ValueError(msg)
    hub_data["repos"] = hub_repos + overlay_repos

    output.parent.mkdir(parents=True, exist_ok=True)
    merged_yaml = yaml.dump(hub_data, Dumper=_IndentedListDumper, default_flow_style=False, sort_keys=False)
    output.write_text(GENERATED_HEADER + "---\n" + merged_yaml + "...\n", encoding="utf-8")

    return MergeResult.MERGED
